[build]
  command = "cd client && pnpm install && pnpm run build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "22"
  PNPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

